version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-server